"""Generate include/game/addresses.h from tools/addresses.tsv.

Note for anyone re-running the source rewrite: absolute branch targets appear as `b`,
`bl` AND every conditional form (`beq`, `bne`, `blt`, ...). Matching only `b`/`bl` misses
them, which is silent on 1.0 -- the literal is correct there -- and a wild branch on 1.1.
The pattern to use is:
    \\b(b|bl)(eq|ne|cs|cc|mi|pl|vs|vc|hi|ls|ge|lt|gt|le|al|hs|lo)?\\s+(0x[0-9A-Fa-f]+)
and comments (everything after `@`) must be stripped first.

The TSV is the checked-in source of truth: one row per symbol, with its USA 1.0 address
and its USA 1.1 address ("-" when not yet known). Deliberately a data file rather than
something scraped out of the sources -- once the sources reference ADDR_* macros there
are no literals left to scrape, so a scraping generator cannot regenerate its own input.

The emitted header is preprocessor-only, so the same definitions serve the C++, the
preprocessed assembly (.S) and mm.ld.in via arm-none-eabi-cpp.

A symbol with no 1.1 address is emitted as a comment for that version, so a 1.1 build
fails loudly on the exact symbol instead of silently linking a 1.0 address.

Usage: python3 tools/genaddrs.py [-o include/game/addresses.h]
"""
import os
import sys

# Anchored to this script, not the working directory: the Makefile invokes it
# from code/ and a person will run it from the repo root.
_HERE = os.path.dirname(os.path.abspath(__file__))
TSV = os.path.join(_HERE, 'addresses.tsv')
OUT = os.path.join(_HERE, '..', 'code', 'include', 'game', 'addresses.h')


def rows():
    for line in open(TSV):
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        name, a10, a11 = line.split('\t')[:3]
        yield name, int(a10, 16), (None if a11.strip() == '-' else int(a11, 16))


def main():
    out = sys.argv[sys.argv.index('-o') + 1] if '-o' in sys.argv else OUT
    table = list(rows())
    missing = [n for n, _, b in table if b is None]

    with open(out, 'w') as f:
        f.write('#pragma once\n\n')
        f.write('// Generated by tools/genaddrs.py from tools/addresses.tsv -- do not edit by hand.\n')
        f.write('// Preprocessor-only so C++, .S assembly and mm.ld.in can all include it.\n')
        f.write('// %d symbols; %d still unmapped for USA 1.1.\n\n' % (len(table), len(missing)))
        f.write('#if defined(Z3D_USA_11)\n\n')
        for name, _, b in table:
            if b is None:
                f.write('// UNMAPPED for 1.1: ADDR_%s\n' % name)
            else:
                f.write('#define ADDR_%-52s 0x%06X\n' % (name, b))
        f.write('\n#else  // USA 1.0\n\n')
        for name, a, _ in table:
            f.write('#define ADDR_%-52s 0x%06X\n' % (name, a))
        f.write('\n#endif\n')

    print('wrote %s: %d symbols, %d unmapped for 1.1' % (out, len(table), len(missing)))
    if missing:
        print('  ' + ', '.join(missing))


if __name__ == '__main__':
    main()
