"""Generate the week event flag name table from game/weekeventreg.h.

There are 140 registers of 8 bits, and 1117 named bitfields -- but 85% of those
names are placeholders of the form WEEKEVENTREG_<reg>_<mask>, which say nothing
the register and bit number do not. Storing all of them would cost 30 KB to tell
the reader what the index already tells them.

So only the meaningful names are emitted, as (index, name) pairs sorted by
index for a binary search. Everything else the menu renders as "bit N".

The WEEKEVENTREG_ prefix is stripped: it is on every single one.

Usage: python3 tools/genflags.py
"""
import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(_HERE, '..', 'code', 'include', 'game', 'weekeventreg.h')
OUT = os.path.join(_HERE, '..', 'code', 'include', 'game', 'weekeventreg_names.h')

PLACEHOLDER = re.compile(r'^WEEKEVENTREG_[0-9]+_[0-9A-Fa-f]+$')


def main():
    src = open(SRC).read()
    entries = []
    reg = None
    for line in src.splitlines():
        m = re.search(r'union WeekEventReg(\d+)\s*\{', line)
        if m:
            reg = int(m.group(1))
            continue
        m = re.search(r'BitField<(\d+), 1, u8> (\w+);', line)
        if m and reg is not None:
            bit, name = int(m.group(1)), m.group(2)
            if PLACEHOLDER.match(name):
                continue
            entries.append((reg * 8 + bit, name.replace('WEEKEVENTREG_', '', 1)))

    entries.sort()
    # Count the unions, not the named flags: registers past the last named one
    # still exist and still need listing.
    regs = len(re.findall(r"union WeekEventReg\d+\s*\{", src))

    with open(OUT, 'w') as f:
        f.write('#pragma once\n\n')
        f.write('// Generated by tools/genflags.py from weekeventreg.h -- do not edit by hand.\n')
        f.write('// %d named flags out of %d registers; the rest are shown as "bit N".\n\n'
                % (len(entries), regs))
        f.write('#include "common/types.h"\n\n')
        f.write('namespace game {\n\n')
        f.write('  struct WeekEventFlagName {\n    u16 index;  // register * 8 + bit\n'
                '    const char* name;\n  };\n\n')
        f.write('  // Sorted by index; look up with a binary search.\n')
        f.write('  static constexpr WeekEventFlagName kWeekEventFlagNames[] = {\n')
        for idx, name in entries:
            f.write('      {%4d, "%s"},\n' % (idx, name))
        f.write('  };\n\n')
        f.write('  static constexpr u32 kWeekEventRegCount = %d;\n\n' % regs)
        f.write('}  // namespace game\n')

    print('wrote %s: %d named flags, %d registers' % (OUT, len(entries), regs))


if __name__ == '__main__':
    main()
